name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test-report:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run cucumber tests
      uses: cucumber/cucumber-action@v3
      with:
        features: src/test/resources/features
        glue: stepdefs
        tags: "@api1"
        plugin: "pretty,com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"

    - name: Copy report file to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        folder: test-output/reports
        destination: /reports

    - name: Rename report file
      run: |
        mv /reports/index.html SmokeTest-$(date +%Y%m%d%H%M%S).html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
