name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test-report:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Generate Extent Report
      run: |
        mvn extent:generate
        mv target/failsafe-reports/extent.html test-output/reports/SmokeTest-$(date +%Y%m%d%H%M%S).html

    - name: Copy report file to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        folder: test-output/reports
        destination: /reports

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
