name: Java CI with Maven and Extent Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test-report:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run tests
      run: mvn test -Dtestng.xml=testng.xml -Dcucumber.options=--plugin com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:test-output/ExtentReport/report.html

    - name: Copy report file to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        folder: test-output/ExtentReport/report.html
        destination: /reports

    - name: Rename report file
      run: |
        mv /reports/report.html /reports/SmokeTest-$(date +%Y%m%d%H%M%S).html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
